JSON_RPC_endpoint: https://rpc.ankr.com/eth

block_range: 
  start: 17000000
  end: 17005000  
  txn_details: True

limit_per_second: 50
sleep_on_error: 10 

anomaly_threshold: 4  # Set at 4 since the likelihood of an entry being further away more than 4 standard deviations from the mean is theoretically 0